redis:
  host: 127.0.0.1
  port: 6379
  user:
  password:
  db: 0
sql:
  host: 127.0.0.1
  port: 3307
  user: root
  password: rootpassword
  db: mydatabase
es:
  protocol: http
  host: 127.0.0.1
  port: 9200
  user: elastic
  password: changeme


server:
  test_account:
    email: daniel.guan@shell.fans
    password: 983B0ca2

  target_page:
    page_id: 365914203781117

  social_midia:
    fb:
      recapture:
        picture_save_path: "./pictures/"
